apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
data:
  n8n.env: |
    DB_TYPE=sqlite
    DB_SQLITE_VACUUM_ON_STARTUP=true
    N8N_HOST=n8n.localhost
    N8N_PORT=5678
    N8N_PROTOCOL=http
    N8N_BASIC_AUTH_ACTIVE=true
    N8N_BASIC_AUTH_USER=root
    N8N_BASIC_AUTH_PASSWORD=123456
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: n8nio/n8n
          ports:
            - containerPort: 5678
          envFrom:
            - configMapRef:
                name: n8n-config
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
spec:
  type: ClusterIP
  selector:
    app: n8n
  ports:
    - port: 5678
      targetPort: 5678